// This file is auto-generated by scripts/generate-code-examples.js
// Do not edit manually.

import examples from './code-examples.json';

export const actionAsync: string = (examples as any)['actionAsync'];
export const actionBasicUsage: string = (examples as any)['actionBasicUsage'];
export const actionBatching: string = (examples as any)['actionBatching'];
export const actionComplexState: string = (examples as any)[
  'actionComplexState'
];
export const actionComposition: string = (examples as any)['actionComposition'];
export const actionDebugging: string = (examples as any)['actionDebugging'];
export const actionErrorHandling: string = (examples as any)[
  'actionErrorHandling'
];
// arrayState examples removed
export const arraystateapi: string = (examples as any)['arraystateapi'];
export const arraystateapi2: string = (examples as any)['arraystateapi2'];
export const arraystateapi3: string = (examples as any)['arraystateapi3'];
export const arraystateapi4: string = (examples as any)['arraystateapi4'];
export const arraystateapi5: string = (examples as any)['arraystateapi5'];
export const arraystateapi6: string = (examples as any)['arraystateapi6'];
export const arraystateapi7: string = (examples as any)['arraystateapi7'];
export const arraystateapi8: string = (examples as any)['arraystateapi8'];
export const arraystateapi9: string = (examples as any)['arraystateapi9'];
export const asyncdataloading: string = (examples as any)['asyncdataloading'];
export const asyncdataloading2: string = (examples as any)['asyncdataloading2'];
export const asyncdataloading3: string = (examples as any)['asyncdataloading3'];
export const asyncdataloading4: string = (examples as any)['asyncdataloading4'];
export const asyncdataloading5: string = (examples as any)['asyncdataloading5'];
export const asyncdataloading6: string = (examples as any)['asyncdataloading6'];
export const batchapi: string = (examples as any)['batchapi'];
export const batchapi10: string = (examples as any)['batchapi10'];
export const batchapi2: string = (examples as any)['batchapi2'];
export const batchapi3: string = (examples as any)['batchapi3'];
export const batchapi4: string = (examples as any)['batchapi4'];
export const batchapi5: string = (examples as any)['batchapi5'];
export const batchapi6: string = (examples as any)['batchapi6'];
export const batchapi7: string = (examples as any)['batchapi7'];
export const batchapi8: string = (examples as any)['batchapi8'];
export const batchapi9: string = (examples as any)['batchapi9'];
export const batching: string = (examples as any)['batching'];
export const batching2: string = (examples as any)['batching2'];
export const batching3: string = (examples as any)['batching3'];
export const batching4: string = (examples as any)['batching4'];
export const batching5: string = (examples as any)['batching5'];
export const batching6: string = (examples as any)['batching6'];
export const batching7: string = (examples as any)['batching7'];
export const batching8: string = (examples as any)['batching8'];
export const derivedapicontent: string = (examples as any)['derivedapicontent'];
export const derivedapicontent2: string = (examples as any)[
  'derivedapicontent2'
];
export const derivedapicontent3: string = (examples as any)[
  'derivedapicontent3'
];
export const derivedapicontent4: string = (examples as any)[
  'derivedapicontent4'
];
export const derivedapicontent5: string = (examples as any)[
  'derivedapicontent5'
];
export const derivedapicontent6: string = (examples as any)[
  'derivedapicontent6'
];
export const derivedapicontent7: string = (examples as any)[
  'derivedapicontent7'
];
export const derivedapicontent8: string = (examples as any)[
  'derivedapicontent8'
];
export const derivedapicontent9: string = (examples as any)[
  'derivedapicontent9'
];
export const derivedvalues: string = (examples as any)['derivedvalues'];
export const derivedvalues2: string = (examples as any)['derivedvalues2'];
export const derivedvalues3: string = (examples as any)['derivedvalues3'];
export const derivedvalues4: string = (examples as any)['derivedvalues4'];
export const effectapicontent: string = (examples as any)['effectapicontent'];
export const effectapicontent10: string = (examples as any)[
  'effectapicontent10'
];
export const effectapicontent11: string = (examples as any)[
  'effectapicontent11'
];
export const effectapicontent12: string = (examples as any)[
  'effectapicontent12'
];
export const effectapicontent13: string = (examples as any)[
  'effectapicontent13'
];
export const effectapicontent14: string = (examples as any)[
  'effectapicontent14'
];
export const effectapicontent15: string = (examples as any)[
  'effectapicontent15'
];
export const effectapicontent16: string = (examples as any)[
  'effectapicontent16'
];
export const effectapicontent17: string = (examples as any)[
  'effectapicontent17'
];
export const effectapicontent2: string = (examples as any)['effectapicontent2'];
export const effectapicontent3: string = (examples as any)['effectapicontent3'];
export const effectapicontent4: string = (examples as any)['effectapicontent4'];
export const effectapicontent5: string = (examples as any)['effectapicontent5'];
export const effectapicontent6: string = (examples as any)['effectapicontent6'];
export const effectapicontent7: string = (examples as any)['effectapicontent7'];
export const effectapicontent8: string = (examples as any)['effectapicontent8'];
export const effectapicontent9: string = (examples as any)['effectapicontent9'];
export const effects: string = (examples as any)['effects'];
export const effects2: string = (examples as any)['effects2'];
export const effects3: string = (examples as any)['effects3'];
export const effects4: string = (examples as any)['effects4'];
export const effects5: string = (examples as any)['effects5'];
export const effects6: string = (examples as any)['effects6'];
export const eslint: string = (examples as any)['eslint'];
export const eslint2: string = (examples as any)['eslint2'];
export const eslint3: string = (examples as any)['eslint3'];
export const eslint4: string = (examples as any)['eslint4'];
export const eslint5: string = (examples as any)['eslint5'];
export const filteringsorting: string = (examples as any)['filteringsorting'];
export const filteringsorting2: string = (examples as any)['filteringsorting2'];
export const filteringsorting3: string = (examples as any)['filteringsorting3'];
export const filteringsorting4: string = (examples as any)['filteringsorting4'];
export const filteringsorting5: string = (examples as any)['filteringsorting5'];
export const filteringsorting6: string = (examples as any)['filteringsorting6'];
export const formvalidation: string = (examples as any)['formvalidation'];
export const formvalidation2: string = (examples as any)['formvalidation2'];
export const formvalidation3: string = (examples as any)['formvalidation3'];
export const formvalidation4: string = (examples as any)['formvalidation4'];
export const formvalidation5: string = (examples as any)['formvalidation5'];
export const installation: string = (examples as any)['installation'];
export const introduction2: string = (examples as any)['introduction2'];
export const introduction3: string = (examples as any)['introduction3'];
export const keyboardshortcuts: string = (examples as any)['keyboardshortcuts'];
export const keyboardshortcuts2: string = (examples as any)[
  'keyboardshortcuts2'
];
export const keyboardshortcuts3: string = (examples as any)[
  'keyboardshortcuts3'
];
export const keyboardshortcuts4: string = (examples as any)[
  'keyboardshortcuts4'
];
export const keyboardshortcuts5: string = (examples as any)[
  'keyboardshortcuts5'
];
export const keyboardshortcuts6: string = (examples as any)[
  'keyboardshortcuts6'
];
export const keyboardshortcuts7: string = (examples as any)[
  'keyboardshortcuts7'
];
export const localstorage: string = (examples as any)['localstorage'];
export const localstorage2: string = (examples as any)['localstorage2'];
export const localstorage3: string = (examples as any)['localstorage3'];
export const localstorage4: string = (examples as any)['localstorage4'];
export const localstorage5: string = (examples as any)['localstorage5'];
export const localstorage6: string = (examples as any)['localstorage6'];
export const localstorage7: string = (examples as any)['localstorage7'];
export const performanceoptimization: string = (examples as any)[
  'performanceoptimization'
];
export const performanceoptimization10: string = (examples as any)[
  'performanceoptimization10'
];
export const performanceoptimization11: string = (examples as any)[
  'performanceoptimization11'
];
export const performanceoptimization2: string = (examples as any)[
  'performanceoptimization2'
];
export const performanceoptimization3: string = (examples as any)[
  'performanceoptimization3'
];
export const performanceoptimization4: string = (examples as any)[
  'performanceoptimization4'
];
export const performanceoptimization5: string = (examples as any)[
  'performanceoptimization5'
];
export const performanceoptimization6: string = (examples as any)[
  'performanceoptimization6'
];
export const performanceoptimization7: string = (examples as any)[
  'performanceoptimization7'
];
export const performanceoptimization8: string = (examples as any)[
  'performanceoptimization8'
];
export const performanceoptimization9: string = (examples as any)[
  'performanceoptimization9'
];
export const quickstart: string = (examples as any)['quickstart'];
export const quickstart2: string = (examples as any)['quickstart2'];
export const quickstart3: string = (examples as any)['quickstart3'];
export const quickstartArrays: string = (examples as any)['quickstartArrays'];
export const quickstartBasicCounter: string = (examples as any)[
  'quickstartBasicCounter'
];
export const quickstartBatching: string = (examples as any)[
  'quickstartBatching'
];
export const quickstartDerivedState: string = (examples as any)[
  'quickstartDerivedState'
];
export const quickstartEffects: string = (examples as any)['quickstartEffects'];
export const quickstartObjects: string = (examples as any)['quickstartObjects'];
export const stateManagementArrayState: string = (examples as any)[
  'stateManagementArrayState'
];
export const stateManagementComposition: string = (examples as any)[
  'stateManagementComposition'
];
export const stateManagementCreatingState: string = (examples as any)[
  'stateManagementCreatingState'
];
export const stateManagementEntityPattern: string = (examples as any)[
  'stateManagementEntityPattern'
];
export const stateManagementNormalization: string = (examples as any)[
  'stateManagementNormalization'
];
export const stateManagementPerformance: string = (examples as any)[
  'stateManagementPerformance'
];
export const stateManagementReadingState: string = (examples as any)[
  'stateManagementReadingState'
];
export const stateManagementUpdates: string = (examples as any)[
  'stateManagementUpdates'
];
export const stateapicontent: string = (examples as any)['stateapicontent'];
export const stateapicontent10: string = (examples as any)['stateapicontent10'];
export const stateapicontent11: string = (examples as any)['stateapicontent11'];
export const stateapicontent2: string = (examples as any)['stateapicontent2'];
export const stateapicontent3: string = (examples as any)['stateapicontent3'];
export const stateapicontent4: string = (examples as any)['stateapicontent4'];
export const stateapicontent5: string = (examples as any)['stateapicontent5'];
export const stateapicontent6: string = (examples as any)['stateapicontent6'];
export const stateapicontent7: string = (examples as any)['stateapicontent7'];
export const stateapicontent8: string = (examples as any)['stateapicontent8'];
export const stateapicontent9: string = (examples as any)['stateapicontent9'];
export const statecomposition: string = (examples as any)['statecomposition'];
export const statecomposition2: string = (examples as any)['statecomposition2'];
export const statecomposition3: string = (examples as any)['statecomposition3'];
export const statecomposition4: string = (examples as any)['statecomposition4'];
export const statemanagement: string = (examples as any)['statemanagement'];
export const statemanagement10: string = (examples as any)['statemanagement10'];
export const statemanagement2: string = (examples as any)['statemanagement2'];
export const statemanagement3: string = (examples as any)['statemanagement3'];
export const statemanagement4: string = (examples as any)['statemanagement4'];
export const statemanagement5: string = (examples as any)['statemanagement5'];
export const statemanagement6: string = (examples as any)['statemanagement6'];
export const statemanagement7: string = (examples as any)['statemanagement7'];
export const statemanagement8: string = (examples as any)['statemanagement8'];
export const statemanagement9: string = (examples as any)['statemanagement9'];
export const storepattern: string = (examples as any)['storepattern'];
export const storepattern2: string = (examples as any)['storepattern2'];
export const storepattern3: string = (examples as any)['storepattern3'];
export const storepattern4: string = (examples as any)['storepattern4'];
export const storepattern5: string = (examples as any)['storepattern5'];
export const storepattern6: string = (examples as any)['storepattern6'];
export const storepattern7: string = (examples as any)['storepattern7'];
export const testing: string = (examples as any)['testing'];
export const testing2: string = (examples as any)['testing2'];
export const testing3: string = (examples as any)['testing3'];
export const testing4: string = (examples as any)['testing4'];
export const testing5: string = (examples as any)['testing5'];
export const testing6: string = (examples as any)['testing6'];
export const testing7: string = (examples as any)['testing7'];
export const testing8: string = (examples as any)['testing8'];
export const useunderstateapicontent: string = (examples as any)[
  'useunderstateapicontent'
];
export const useunderstateapicontent10: string = (examples as any)[
  'useunderstateapicontent10'
];
export const useunderstateapicontent11: string = (examples as any)[
  'useunderstateapicontent11'
];
export const useunderstateapicontent12: string = (examples as any)[
  'useunderstateapicontent12'
];
export const useunderstateapicontent2: string = (examples as any)[
  'useunderstateapicontent2'
];
export const useunderstateapicontent3: string = (examples as any)[
  'useunderstateapicontent3'
];
export const useunderstateapicontent4: string = (examples as any)[
  'useunderstateapicontent4'
];
export const useunderstateapicontent5: string = (examples as any)[
  'useunderstateapicontent5'
];
export const useunderstateapicontent6: string = (examples as any)[
  'useunderstateapicontent6'
];
export const useunderstateapicontent7: string = (examples as any)[
  'useunderstateapicontent7'
];
export const useunderstateapicontent8: string = (examples as any)[
  'useunderstateapicontent8'
];
export const useunderstateapicontent9: string = (examples as any)[
  'useunderstateapicontent9'
];
