module.exports = {
  rules: {
    'require-use-subscribe': require('./rules/require-use-subscribe.cjs'),
    'require-use-subscribe-store-object': require('./rules/require-use-subscribe-store-object.cjs'),
    'prefer-batch-for-multiple-updates': require('./rules/prefer-batch-for-multiple-updates.cjs'),
    'no-direct-state-assignment': require('./rules/no-direct-state-assignment.cjs'),
    'require-use-subscribe-for-all-states': require('./rules/require-use-subscribe-for-all-states.cjs'),
    'prefer-derived-for-computed': require('./rules/prefer-derived-for-computed.cjs'),
    'no-state-creation-in-components': require('./rules/no-state-creation-in-components.cjs'),
    'prefer-effect-for-side-effects': require('./rules/prefer-effect-for-side-effects.cjs'),
    'no-unused-states': require('./rules/no-unused-states.cjs'),
    'require-error-handling-in-async-updates': require('./rules/require-error-handling-in-async-updates.cjs'),
    'prefer-object-spread-for-updates': require('./rules/prefer-object-spread-for-updates.cjs'),
    'no-nested-effects': require('./rules/no-nested-effects.cjs'),
    'no-nested-derived': require('./rules/no-nested-derived.cjs'),
    'no-library-functions-in-actions': require('./rules/no-library-functions-in-actions.cjs'),
    'no-state-creation-in-effects': require('./rules/no-state-creation-in-effects.cjs'),
    'no-derived-creation-in-effects': require('./rules/no-derived-creation-in-effects.cjs'),
    'no-state-updates-in-derived': require('./rules/no-state-updates-in-derived.cjs'),
    'no-effect-creation-in-derived': require('./rules/no-effect-creation-in-derived.cjs'),
    'require-error-handling-in-effects': require('./rules/require-error-handling-in-effects.cjs'),
    'no-direct-state-mutation': require('./rules/no-direct-state-mutation.cjs'),
    'no-unused-action-parameters': require('./rules/no-unused-action-parameters.cjs'),
    'require-state-subscription-cleanup': require('./rules/require-state-subscription-cleanup.cjs'),
  },
  configs: {
    recommended: {
      plugins: ['react-understate'],
      rules: {
        // Error rules - these are critical for correct usage
        'react-understate/require-use-subscribe-for-all-states': 'error',
        'react-understate/require-use-subscribe-store-object': 'error',
        'react-understate/no-direct-state-assignment': 'error',
        'react-understate/no-state-creation-in-components': 'error',
        'react-understate/no-nested-effects': 'error',
        'react-understate/no-nested-derived': 'error',
        'react-understate/no-library-functions-in-actions': 'error',
        'react-understate/no-state-creation-in-effects': 'error',
        'react-understate/no-derived-creation-in-effects': 'error',
        'react-understate/no-state-updates-in-derived': 'error',
        'react-understate/no-effect-creation-in-derived': 'error',
        'react-understate/require-error-handling-in-effects': 'warn',
        'react-understate/no-direct-state-mutation': 'error',
        'react-understate/no-unused-action-parameters': 'warn',
        'react-understate/require-state-subscription-cleanup': 'warn',

        // Warning rules - these are best practices but not critical
        'react-understate/prefer-derived-for-computed': 'warn',
        'react-understate/prefer-effect-for-side-effects': 'warn',
        'react-understate/no-unused-states': 'warn',
        'react-understate/require-error-handling-in-async-updates': 'warn',
        'react-understate/prefer-object-spread-for-updates': 'warn',
        'react-understate/prefer-batch-for-multiple-updates': 'warn',
      },
    },
  },
};
